**for**: sentencia que se usa para generar iteraciones o también llamados bucles

In [27]:
resultado=[]

In [28]:
for i in range(2,11):
    resultado.append(i**2)
resultado

[4, 9, 16, 25, 36, 49, 64, 81, 100]

In [5]:
resultado

[4, 9, 16, 25, 36, 49, 64, 81, 100]

- **append()**: la función append se utiliza para ir agregando elementos a un objeto

**while**: realiza un recorrido sobre valores, pero es condicional, por eso toma el nombre de bucle condicional

In [6]:
x=0
y=20

In [7]:
while x<y:
    print(x)
    x+=1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


**tipeado dinámico**

In [8]:
lista = [2,3,4,5]; print(lista)

[2, 3, 4, 5]


In [9]:
lista2 = lista; print(lista2)

[2, 3, 4, 5]


**Nota**: modificamos un valor en el objeto lista

In [11]:
lista[0]=100

In [12]:
print(lista)

[100, 3, 4, 5]


In [13]:
print(lista2)

[100, 3, 4, 5]


In [14]:
lista2=lista.copy()

In [16]:
lista[0]=2

In [17]:
lista

[2, 3, 4, 5]

In [18]:
lista2

[100, 3, 4, 5]

In [ ]:
cálculos / segundo realiza tu ordenador

In [ ]:
mil registros

In [19]:
1000*1000

1000000

In [22]:
((1000000/15)/60)/60

18.51851851851852

In [ ]:
h2o para python (trabaja en un clúster de procesamiento paralelo de doce núcleos)

In [ ]:
h2o para R (trabaja con un núcleo de procesamiento)

**Estructuras de objetos**

**Números**

In [32]:
n_entero = 40; print(n_entero); type(n_entero)

40


int

In [39]:
n_real = 11.0; print(n_real); type(n_real)

11.0


float

**sistemas numéricos**

In [41]:
n_bin = 0b11; print(n_bin)

3


In [43]:
bin(3)

'0b11'

**Nota**: para python no es un problema trabajar con diferentes sistemas numéricos, ya que los convierte en el sistema decimal

In [44]:
n_hex = 0xf; print(n_hex)

15


In [45]:
hex(15)

'0xf'

**Conjuntos**

In [48]:
conjunto = {2,3,4,10,11,15};type(conjunto);print(conjunto)

{2, 3, 4, 10, 11, 15}


In [49]:
conjunto2 = {3,11,19,21}

In [50]:
conjunto & conjunto2

{3, 11}

In [51]:
conjunto.intersection(conjunto2)

{3, 11}

In [52]:
duplicados = {2,3,4,4,5,6,9,11,11,23}

In [53]:
print(duplicados)

{2, 3, 4, 5, 6, 9, 11, 23}


**Cadena de texto**

In [54]:
cadena = "este es un objeto tipo texto"

In [55]:
print(cadena)

este es un objeto tipo texto


In [56]:
type(cadena)

str

**Nota**: los objetos tipo texto su formato es object o string

**pandas.read_csv()**: función para importar ficheros csv

parámetro encoding=None

In [57]:
bytearray("Sigüeñas","latin")

bytearray(b'Sig\xfce\xf1as')

In [59]:
bytearray("Sigüeñas","cp273")

bytearray(b'\xe2\x89\x87\xd0\x85I\x81\xa2')

https://docs.python.org/3/library/codecs.html#standard-encodings

**Listas**

- nos permite almacenar valores u objetos de diferentes tipos (o formatos)- se diferencia de los vectores
- se pueden modificar después de crearlas - se diferencia de las tuplas.
- se define usando []

In [61]:
alumno = ["Miguel",24,True];type(alumno)

list

In [63]:
alumno[1]=26

In [64]:
print(alumno)

['Miguel', 26, True]


In [65]:
alumno.append("Miraflores")

In [66]:
print(alumno)

['Miguel', 26, True, 'Miraflores']


In [67]:
alumno.insert(1,"Jacinto")

In [68]:
print(alumno)

['Miguel', 'Jacinto', 26, True, 'Miraflores']


In [69]:
del alumno[1]

In [70]:
alumno

['Miguel', 26, True, 'Miraflores']

In [71]:
alumnos = [["Miguel",24,True],["Ibrahim",30,True]]

In [80]:
alumnos[1][0]="Ibrahim"

In [77]:
alumnos[1][0]=alumnos[1][0].replace("Ibrahim","Perez")

In [81]:
alumnos

[['Miguel', 24, True], ['Ibrahim', 30, True]]

**Ejemplo de crear un DF a partir de una lista de listas**

In [82]:
import pandas as pd

In [84]:
data=pd.DataFrame(alumnos,#lista de listas
            columns=["nombre","edad","sexo=masculino"])

In [85]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   nombre          2 non-null      object
 1   edad            2 non-null      int64 
 2   sexo=masculino  2 non-null      bool  
dtypes: bool(1), int64(1), object(1)
memory usage: 162.0+ bytes


In [86]:
import os
os.getcwd()

'C:\\Users\\SOCIAL DATA'

**Tuplas**

- una vez que es creado es un objeto inmodificable

In [87]:
alumno_tupla = "Ibrahim",30,True

In [89]:
alumno_tupla[1]=32

TypeError: 'tuple' object does not support item assignment

**¿Podríamos modificar una tupla a otra estructura de objeto?**

In [90]:
alumno_list = list(alumno_tupla)

In [91]:
type(alumno_list)

list

In [92]:
alumno_list

['Ibrahim', 30, True]

**Vectores & matrices**

In [29]:
import numpy as np

In [94]:
np.array([25,30,32,"28"])

array(['25', '30', '32', '28'], dtype='<U11')

- son objetos que admiten un tipo de formato

In [95]:
edades=np.array([25,30,32,28])

In [97]:
edades[1]=27

In [98]:
print(edades)

[25 27 32 28]


**Diccionarios**

In [99]:
alumno_dict ={"alumno":["Ibrahim","Harol","Enrique","Katherin"],
             "edad":[30,24,28,32],
             "masculino":[True,True,True,False],
             "universidad":["PUCP","UNI","PUCP","UNALM"]}

In [100]:
type(alumno_dict)

dict

In [101]:
print(alumno_dict)

{'alumno': ['Ibrahim', 'Harol', 'Enrique', 'Katherin'], 'edad': [30, 24, 28, 32], 'masculino': [True, True, True, False], 'universidad': ['PUCP', 'UNI', 'PUCP', 'UNALM']}


In [104]:
alumno_dict["alumno"][2]="Oliver"

In [105]:
print(alumno_dict)

{'alumno': ['Ibrahim', 'Harol', 'Oliver', 'Katherin'], 'edad': [30, 24, 28, 32], 'masculino': [True, True, True, False], 'universidad': ['PUCP', 'UNI', 'PUCP', 'UNALM']}


In [106]:
import pandas as pd

In [107]:
df_alumnos = pd.DataFrame(alumno_dict)

In [108]:
df_alumnos

alumno  edad  masculino universidad
0   Ibrahim    30       True        PUCP
1     Harol    24       True         UNI
2    Oliver    28       True        PUCP
3  Katherin    32      False       UNALM

**DataFrame**

In [30]:
import pandas as pd

**algunos ejemplos de manipulación de unDF**

Consultar las etiquetas de una columna de un DF

In [112]:
name_columns= df_alumnos.columns.tolist();print(name_columns)

['alumno', 'edad', 'masculino', 'universidad']


Consultar los valores de columna de un DF

In [113]:
value_x = df_alumnos["edad"].values

In [114]:
value_x

array([30, 24, 28, 32], dtype=int64)

In [116]:
df_alumnos[["edad","universidad"]].values

array([[30, 'PUCP'],
       [24, 'UNI'],
       [28, 'PUCP'],
       [32, 'UNALM']], dtype=object)

In [118]:
df_alumnos.iloc[:,[1,3]].values

array([[30, 'PUCP'],
       [24, 'UNI'],
       [28, 'PUCP'],
       [32, 'UNALM']], dtype=object)

In [119]:
df_alumnos.head(n=2)

alumno  edad  masculino universidad
0  Ibrahim    30       True        PUCP
1    Harol    24       True         UNI

In [120]:
df_alumnos.tail(n=2)

alumno  edad  masculino universidad
2    Oliver    28       True        PUCP
3  Katherin    32      False       UNALM

**¿Cómo generamos una copia del DF?**

In [121]:
data = df_alumnos.copy()

In [123]:
data.iloc[1,1]=26

In [124]:
data.head()

alumno  edad  masculino universidad
0   Ibrahim    30       True        PUCP
1     Harol    26       True         UNI
2    Oliver    28       True        PUCP
3  Katherin    32      False       UNALM

In [128]:
data.drop(columns="edad",#nombre de la columna
         axis=1,#axis=1: sobre columna
         inplace=True) #inplace: definir si se elimina de forma permanente o sólo para la consulta

- axis=1: la operación se hace sobre columnas
- axis=0: la operación se hace sobre filas

In [129]:
data

alumno  masculino universidad
0   Ibrahim       True        PUCP
1     Harol       True         UNI
2    Oliver       True        PUCP
3  Katherin      False       UNALM

In [130]:
data.drop(1,
         axis=0,
         inplace=True)

In [131]:
data

alumno  masculino universidad
0   Ibrahim       True        PUCP
2    Oliver       True        PUCP
3  Katherin      False       UNALM

**reset_index()**

In [132]:
data.reset_index(drop=True)

alumno  masculino universidad
0   Ibrahim       True        PUCP
1    Oliver       True        PUCP
2  Katherin      False       UNALM

In [136]:
df_alumnos

alumno  edad  masculino universidad
0   Ibrahim    30       True        PUCP
1     Harol    24       True         UNI
2    Oliver    28       True        PUCP
3  Katherin    32      False       UNALM

In [139]:
df_alumnos[(df_alumnos.universidad!="PUCP")&(df_alumnos.edad>30)]

alumno  edad  masculino universidad
3  Katherin    32      False       UNALM

In [143]:
df_alumnos.edad.max()

32

In [144]:
df_alumnos.edad.mean()

28.5

In [145]:
df_alumnos.edad.min()

24

**importación de ficheros y conexión a bases de datos**

In [147]:
import json5
import json
import pandas as pd
import pyreadstat
import numpy as np
import os

In [ ]:
pip install pyreadstat

In [148]:
import pyodbc
import psycopg2
import pandas.io.sql

In [150]:
import os
os.getcwd()

'C:\\Users\\SOCIAL DATA'

In [153]:
os.listdir("C:/Users/SOCIAL DATA")

[' Prueba MSV.ipynb',
 '.anaconda_backup',
 '.android',
 '.azure',
 '.azureml',
 '.bash_history',
 '.cache',
 '.conda',
 '.condarc',
 '.git',
 '.gitconfig',
 '.gitignore',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.keras',
 '.matplotlib',
 '.ms-ad',
 '.opera',
 '.pgAdmin4.1590372639.addr',
 '.pgAdmin4.1590372639.log',
 '.pgAdmin4.427924103.addr',
 '.pgAdmin4.427924103.log',
 '.pgAdmin4.startup.log',
 '.pylint.d',
 '.python_history',
 '.RapidMiner',
 '.Rhistory',
 '.spyder',
 '.spyder-py3',
 '.VirtualBox',
 '.vscode',
 '03 - Notebook 6.ipynb',
 '06 Introduccion a la extraccion de patrones.rar',
 '10. Desplegar_consumir_real_time_lab.ipynb',
 '10_Monitoreo_modelos',
 '24. Deriva de datos_lab.ipynb',
 '3D Objects',
 'aaaa.ipynb',
 'abc.ipynb',
 'ACNUR_SESION_1.ipynb',
 'ACNUR_SESION_2.ipynb',
 'ACNUR_tema1.ipynb',
 'ACNUR_tema2.ipynb',
 'ACNUR_tema3.ipynb',
 'ACNUR_tema4.ipynb',
 'ACNUR_tema5.ipynb',
 'ACNUR_tema6.ipynb',
 'ACNUR_tema7.ipynb',
 'ADE_grupo4.ipynb',
 'Ajuste_hiperp

In [154]:
os.chdir("D:/Python/1. Nivel I/3/datos")

In [156]:
os.getcwd()

'D:\\Python\\1. Nivel I\\3\\datos'

In [155]:
os.listdir("D:/Python/1. Nivel I/3/datos")

['anes_timeseries_2012.dta',
 'data_BL.csv',
 'data_buscalibre',
 'data_buscalibre.csv',
 'df_concat.csv',
 'distritos.sav',
 'ElectricBus.xlsx',
 'housing.data.txt',
 'LL.csv',
 'subvenciones.csv',
 'subvenciones.json',
 'subvenciones.ods',
 'subvenciones.tsv',
 'subvenciones.xls',
 'subvenciones.xml',
 'subvenciones_agrupadas.json',
 'subvenciones_agrupadas_con_gasto.json',
 'subvenciones_df.xls',
 'subvenciones_esc.csv',
 'subvenciones_lista_total.xml',
 'subvenciones_totales.xls',
 'tabla_senal.csv']

**Excel**

In [157]:
df_excel = pd.read_excel("subvenciones.xls",
                        sheet_name="Hoja1")

In [159]:
df_excel.head(n=10)

Asociación           Actividad Subvencionada   Importe
0  AMPA ANTONIO MACHADO          TALLER FIESTA DE CARNAVAL    94.56
1  AMPA ANTONIO MACHADO               TALLER DIA DEL PADRE    39.04
2  AMPA ANTONIO MACHADO             TALLER DIA DE LA MADRE    43.64
3  AMPA ANTONIO MACHADO                FIESTA FIN DE CURSO   921.00
4  AMPA ANTONIO MACHADO             CONCURSO LOGOTIPO AMPA    56.57
5  AMPA ANTONIO MACHADO         ASOCIACION FAPA ALCOBENDAS    80.00
6  AMPA ANTONIO MACHADO  ASOCIACION FAPA GINER DE LOS RIOS    86.79
7  AMPA ANTONIO MACHADO                  FIESTA DE NAVIDAD   660.00
8  AMPA ANTONIO MACHADO                          HALLOWEEN   168.39
9  AMPA ANTONIO MACHADO                         SAN ISIDRO   195.00

In [160]:
df_excel.tail(n=10)

Asociación                           Actividad Subvencionada   \
181      AMPA SAN ANTONIO                                     GRANJA ESCUELA   
182      AMPA SAN ANTONIO             VISITA AL PARQUE DE AVENTURAS AMAZONIA   
183      AMPA SAN ANTONIO                        ASISTENCIA AL CIRCO MUNDIAL   
184  AMPA PADRE  MANYANET                        FERIA DE LA SEMANA CULTURAL   
185  AMPA PADRE  MANYANET         BIBLIOTECA DE EDUCACION PRIMARIA DE LA APA   
186  AMPA PADRE  MANYANET                                  FERIA DE ROBOTICA   
187  AMPA PADRE  MANYANET                       LUDOTECA FIESTA FIN DE CURSO   
188             AMPA FAPA     JORNADA FAPA-APAS: ENCUENTROS DE PARTICIPACION   
189             AMPA FAPA                     25 ANIVERSARIO FAPA ALCOBENDAS   
190             AMPA FAPA  REVISTA DE LA FEDERACION "LA ESCUELA EN ALCOBE...   

     Importe  
181   895.00  
182   576.00  
183   630.83  
184   800.00  
185   803.82  
186   720.00  
187   372.00  
188   720.00  
189  1515.00  
190   963.43